version: '2'
services:
  orgchart_mongo:
    hostname: orgchart_mongo
    container_name: orgchart_mongo
    image: mongo
    ports:
      - 27017
    volumes:
      - /home/ewnchui/git/compose/orgchart/data:/data/db 
    
    
  orgchart:
    hostname: orgchart
    container_name: orgchart
    depends_on:
      - orgchart_mongo
    image: ewnchui/orgchart
    ports:
      - 1337
    entrypoint: top -b -d 1000  
    volumes:
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
      - ./config/docker/development.coffee:/usr/src/app/config/env/development.coffee
      - /etc/ssl/certs/mobile.ogcio.hksarg.pem:/etc/ssl/certs/mobile.ogcio.hksarg.pem
      - /usr/local/share/ca-certificates/mobile.ogcio.hksarg.crt:/usr/src/app/ca-certificates/mobile.ogcio.hksarg.crt      